version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: account-management-db
    environment:
      POSTGRES_DB: account_management
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - account-network

volumes:
  pgdata:

networks:
  account-network: